### ISSUE TITLE
register 2.3

### ISSUE THREAD

**Issue by shahriariravanian** [SciML/CellMLToolkit.jl#34]
@JuliaRegistrator register

**Comment by anandijain** [comment]
🎉

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register
