### ISSUE TITLE
Parameters in equations are not marked as parameters

### ISSUE THREAD

**Issue by YingboMa** [SciML/CellMLToolkit.jl#47]
```julia
julia> collect(ModelingToolkit.vars(equations(ss)[1].rhs))[1] |> dump
Sym{Real, Nothing}
  name: Symbol C
  metadata: Nothing nothing
julia> collect(ModelingToolkit.vars(equations(ss)[1].rhs))[1] |> ModelingToolkit.isparameter
false
julia> parameters(ss)
1-element Vector{Sym{Real, Nothing}}:
 C
```

**Comment by shahriariravanian** [comment]
We are using this function to make a param:

```julia
function create_param(x)
  p = Sym{Real}(Symbol(x))
  ModelingToolkit.toparam(p)
  p
end
```

But, if `x = create_param(:x)`, then we have `typeof(x) == Sym{Real, Nothing}`. What is the correct function to generate a param?

**Comment by shahriariravanian** [comment]
It seems this function works fine

```julia
function create_param(x)
  @parameters p
  ModelingToolkit.rename(p.val, Symbol(x))
end
```

**Comment by shahriariravanian** [comment]
Another possibility is simply `create_param(x) =  eval(:(@parameters $x))[1]`. Given the MTK data structures are in flux, this solution is probably the most stable option for the time being.

**Comment by YingboMa** [comment]
The parameter generations are fine, but the parameter information is not in equations.

**Comment by shahriariravanian** [comment]
The old version, 

```julia
function create_param(x)
  p = Sym{Real}(Symbol(x))
  ModelingToolkit.toparam(p)
  p
end
```

does not work fine. The output is not a parameter. The new version 

```julia
function create_param(x)
  @parameters p
  ModelingToolkit.rename(p.val, Symbol(x))
end
```

returns a parameter.
